import type { Metadata } from "next";
import {
    ClerkProvider,
} from '@clerk/nextjs'
import { Manrope } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../react-query/index"
import React from "react";

const manrope = Manrope({
    subsets : ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${manrope.className} bg-[#171717] antialiased`}
            >
            <ReactQueryProvider>
                {children}
            </ReactQueryProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
